### ISSUE TITLE
Quarkus Training

### ISSUE THREAD

**Issue by dmartinol** [RHEcosystemAppEng/DepDraw#17]
Complete the required training to get familiar with Quarkus programming.

[Understanding Quarkus](https://developers.redhat.com/books/understanding-quarkus)
[Practising Quarkus](https://developers.redhat.com/books/practising-quarkus)

**Comment by nemerna** [comment]
following this Workshop for learning
https://quarkus.io/quarkus-workshops/super-heroes/#_running_the_default_health_check

As we talked it cover the same topics covered in the resources you attached

will keep the issue updated with my progress
