### ISSUE TITLE
Design the initial design of the Data Model 

### ISSUE THREAD

**Issue by nemerna** [RHEcosystemAppEng/DepDraw#23]
we need to design the following points in order to have more clarity over the APIs that will be offered by each MS:

1) what k8s resources will be included in the MVP version?
2) what part of each resource we will be supporting (partial fields / all fields) consider that using partial fields will require us to define the k8s resources schemas instead of using the official ones.
3) design how data will be handled (how to represent a diagram, shape, connector)
4) design how to link between a k8s resource schema with a Diagram Shape.

**Comment by nemerna** [comment]
1) what k8s resources will be included in the MVP version?

"Pod", "Service", "Route", "Deployment", "Statefulset", "Project", "Namespace"

open for discussion:
support for storage such as (PV, PVC, and Storageclass)
if supported, will we be handling them as standalone objects/shapes


2) this question is open for discussion...

3) adding 4 JSON schemas under the "json-schemas" directory in this issue branch as I can't attach files to comment here in GH
- Diagram-schema.json which represents the Diagram schema, where sub-schemas are referenced (shapes and connectors)
- Shape-schema.json which represents a shape schema
- Connector-schema.json which represents a Connector schema
- all-in-one.json which represents a diagram schema where sub-schemas are not a reference, but the definition itself

4) according to the design of the shape schema, each shape has a type that references a k8s resource name, so assuming we have all of the supported k8s-resources schemas in our datastore or somewhere online, we can reference each shape with the corresponding k8s resource schema according to the "shape.type". -- open for discussion

in case we agree on the proposed schemas and data model, I assume the following actions to be taken is to work on the dataservice MS to develop the possible APIs of CRUD over those schemas after deciding what DB type we will be using for storing those data.

**Comment by nemerna** [comment]
@dmartinol I think we will need to discuss the above in a call,
unless you got some written message for me changing critical things that I made not as planned, or things that I have missed so I could add them before we meet.

**Comment by nemerna** [comment]
additionally 
I have built a Diagram Object according to the proposed schemas,
where the diagram contains a project, and the project shape contains a "pod, service, and route"
where the service is being linked to the pod with a connector of type "sync-selectors"
where the route is being linked to the service with a connector of type "sync-selectors"
additionally, the Pod is inheriting the service labels as they are linked with an additional connector of type  "inherit labels"

well, now I realize that I have missed having a "Name" field for the Shape schema where each shape can have its own name,
but this can be done as a patch, for now, let's see if we are going in the correct direction.


attaching a picture that makes it easy to understand what is defined in the Diagram Json instance

![image](https://user-images.githubusercontent.com/90598979/204239602-8ea94435-8cd2-4885-a386-e4aa300dc2e8.png)

**Comment by dmartinol** [comment]
@nemerna looks a good starting point to continue the discussion, even if I don't see where we can configure the K8s resources in this schema.
If we don't want to reinvent the wheel and use the official (versioned) schema, we need a separate place for that.
Please schedule a call to continue the investigation

**Comment by nemerna** [comment]
Discussion Notes:

1) we are using file storage temporarily till the MVP release

2)the supported k8s resources are:
"Pod", "Service", "Route", "Deployment", "Statefulset", "Namespace".

3)the supported connectors types: e.g "inherit labels"
for discussion with the extended team.

4)expected functionality we want to provide:
datastore:
    Create a Diagram "ATM manually defined json". (watch UID)
    Create a k8s resource.
    update Diagram. (override UID).
    Get Diagram (*maybey* according to path)

k8sClient:
    apply Diagram <- Diagram_ID
    Delete Diagram <- Diagram_ID (according to annotations OR according to aloop over diagram resources )


Transformer:
    apply connectors effects over k8s resources.
    autmoatic add specific annotation to resources to unify under a group (diagram) e.g "Depdraw/Diagram: $DiagramID"


api-server:
    Create a Diagram "ATM manually defined json". (watch UID)
    Create a k8s resource (expects diagram.shapeid) for association.
    apply Diagram <- Diagram_ID 
    apply connectors effects over k8s resources.
    autmoatic add specific annotation to resources to unify under a group (diagram) e.g "Depdraw/Diagram: $DiagramID"
    Get Diagram (*maybey* sub objects in diagram according to path)
---
    Delete Diagram from k8s <- Diagram_ID (according to annotations OR according to aloop over diagram resources )
    Delete the Diagram from DataStore (according to DiagramID)
    List all Diagrams.
    update Diagram. (override UID).
