### ISSUE TITLE
Data Service

### ISSUE THREAD

**Issue by dmartinol** [RHEcosystemAppEng/DepDraw#9]
## Data Service
* Quarkus Java 11/17
* Under src/dataservice/ folder
* groupId: com.redhat.depdraw
* artifactId: dataservice
* version: 0.0.1-SNAPSHOT
* image: dataservice:0.0.1-SNAPSHOT
* REST services:
    * GET /health returns 200

**Comment by dmartinol** [comment]
Acceptance criteria:
- Basic instructions in README to build and run in local machine or container environment
- Possibly UT code to check the /health endpoint
- Dockerfile (for Quarkus it should be generated for free)
- deployment.yaml and service.yaml to deploy in OpenShift and create networking resources (including Route if requested)

**Comment by nemerna** [comment]
@dmartinol just a note, I have changed the java version for compilation into java11.

not sure how critical it is.
